# Install Kepler Exporter from Kepler Chart
kepler:
  # dashboard setting remark: https://www.eia.gov/tools/faqs/faq.php?id=74&t=11
  global:
    namespace: cattle-monitoring-system
  selectorLabels:
      app.kubernetes.io/name: caas-carbon-footprint
  image:
    repository: mtr.devops.telekom.de/caas/kepler
    pullPolicy: Always
    tag: release-0.6.1
  resources:
    limits:
      cpu: 800m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 128Mi

# Install Entsoe Exporter
entsoe:
  enabled: true
  # apply for token here: https://transparency.entsoe.eu/content/static_content/download?path=/Static%20content/API-Token-Management.pdf
  #entsoe_api_key:
  image:
    repository: mtr.devops.telekom.de/caas/entsoe
    tag: 0.0.5
    pullPolicy: Always
  podSecurityContext:
    fsGroup: 1000
    supplementalGroups:
    - 1000
  # proxy settings for outside API requests to https://web-api.tp.entsoe.eu:443
  proxy:
    enabled: false
    #host: 10.0.0.1
    #port: 3128
    #protocol: http
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    privileged: false
    readOnlyRootFilesystem: true
    runAsUser: 1000
    runAsGroup: 1000
  # beware of the API request limit 
  # sec. 1.8 https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html
  serviceMonitor:
    interval: 10m
  # hours back when entsoe metrics should collected
  # note: sometimes no real time data for Germany, must be at least one day back 
  start: 1
  end: 0
# install app in Rancher environment
# this will user Rancher defined namespaces and labels
rancher:
  enabled: true
  cattleDashboards: false
