kepler:
  global:
    namespace: cattle-monitoring-system
  image:
    repository: mtr.devops.telekom.de/caas/kepler
    pullPolicy: Always
    tag: release-0.6.1
entsoe:
  image:
    repository: mtr.devops.telekom.de/caas/entsoe
    pullPolicy: Always
    tag: latest
