{{ if .Values.entsoe.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: entsoe-{{ include "caas-carbon-footprint.fullname" . }}
  labels:
    app.kubernetes.io/component: entsoe
    {{- include "caas-carbon-footprint.labels" . | nindent 4 }}
spec:
  egress:
  - {}
  ingress:
  - ports:
    - port: 80
      protocol: TCP
    - port: 9091
      protocol: TCP
  podSelector:
    matchLabels:
      {{- include "caas-carbon-footprint.selectorLabels" . | nindent 4 }}
  policyTypes:
  - Ingress
  - Egress
{{ end }}
