{{ if .Values.entsoe.enabled }}
{{ if .Values.entsoe.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "caas-carbon-footprint.labels" . | nindent 4 }}
    {{- if .Values.rancher.enabled }}
    release: rancher-monitoring
    {{- end }}
  name: entsoe-{{ include "caas-carbon-footprint.fullname" . }}
spec:
  endpoints:
  - interval: {{ .Values.entsoe.serviceMonitor.interval }}
    path: /metrics
    port: http
    scheme: http
    relabelings:
    - action: replace
      replacement: caasglobal
      sourceLabels:
      - container
      targetLabel: namespace
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/component: entsoe
      {{- include "caas-carbon-footprint.selectorLabels" . | nindent 6 }}
{{ end }}
{{ end }}
