apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: rancher-monitoring
  name: entsoe
spec:
  endpoints:
  - interval: 30m
    path: /metrics
    port: http
    scheme: http
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app: entsoe
