{{ if .Values.entsoe.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: entsoe-monitor-{{ include "caas-carbon-footprint.fullname" . }}
  labels:
    app.kubernetes.io/component: entsoe
    {{- include "caas-carbon-footprint.labels" . | nindent 4 }}
spec:
  egress:
  - {}
  ingress:
  - ports:
    - port: 80
      protocol: TCP
    - port: 9091
      protocol: TCP
  podSelector:
    matchLabels:
      {{- include "caas-carbon-footprint.selectorLabels" . | nindent 4 }}
  policyTypes:
  - Ingress
  - Egress
{{ if .Values.entsoe.proxy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: entsoe-proxy-{{ include "caas-carbon-footprint.fullname" . }}
spec:
  egress:
  - ports:
    - port: {{ .Values.entsoe.proxy.port }}
      protocol: TCP
    to:
    - ipBlock:
        cidr: {{ .Values.entsoe.proxy.host }}/32
  podSelector:
    matchLabels:
      {{- include "caas-carbon-footprint.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
{{ end }}
{{ end }}
