apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "caas-carbon-footprint.labels" . | nindent 4 }}
    {{- if .Values.rancher.enabled }}
    release: rancher-monitoring
    {{- end }}
  name: {{ include "caas-carbon-footprint.fullname" . }}-kepler
spec:
  endpoints:
  - interval: 30s
    metricRelabelings:
    - action: replace
      regex: (.*)
      sourceLabels:
      - container_namespace
      targetLabel: namespace
    port: http
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
    scheme: http
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kepler
