{
 "title": "CaaS Carbon Dashboard",
 "description": "Dashboard for CaaS Carbon Footprint",
 "tags": [ "sustainable-computing" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kepler_container_package_joules_total{cluster=~\"$meta_cluster\"}, container_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kepler_container_package_joules_total{container_namespace=~\"$namespace\",cluster=~\"$meta_cluster\"}, pod_name)"
    }
   },
   {
    "name": "meta_cluster",
    "label": "Cluster",
    "query": "label_values(prometheus_build_info, cluster)"
   },
   { "name": "watt_per_second_to_kWh", "query": "0.000000277777777777778" },
   { "name": "fosfactor", "query": "751" },
   { "name": "ecofactor", "query": "117" },
   { "name": "biomass", "query": "230" },
   { "name": "browncoal", "query": "996" },
   { "name": "hardcoal", "query": "880" },
   { "name": "gas", "query": "378" },
   { "name": "nuclear", "query": "39" },
   { "name": "windonshore", "query": "9" },
   { "name": "windoffshore", "query": "4" },
   { "name": "solar", "query": "26" },
   { "name": "waste", "query": "494" },
   { "name": "hydropump", "query": "23" },
   { "name": "hydroriver", "query": "23" },
   { "name": "hydrores", "query": "23" }
  ]
 },
 "panels": [
  { "title": "Carbon Emissions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Energy Generation Germany",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(entsoe_generation_b01)", "legendFormat": "Biomass" },
    { "expr": "avg(entsoe_generation_b02)", "legendFormat": "Brown Coal" },
    { "expr": "avg(entsoe_generation_b04)", "legendFormat": "Gas" },
    { "expr": "avg(entsoe_generation_b05)", "legendFormat": "Hard Coal" },
    { "expr": "avg(entsoe_generation_b09)", "legendFormat": "Geothermal" },
    { "expr": "avg(entsoe_generation_b10)", "legendFormat": "Hydro Pumped Storage" },
    { "expr": "avg(entsoe_generation_b11)", "legendFormat": "Hydro Run-of-river" },
    { "expr": "avg(entsoe_generation_b12)", "legendFormat": "Hydro Water Res." },
    { "expr": "avg(entsoe_generation_b14)", "legendFormat": "Nuclear" },
    { "expr": "avg(entsoe_generation_b16)", "legendFormat": "Solar" },
    { "expr": "avg(entsoe_generation_b17)", "legendFormat": "Waste" },
    { "expr": "avg(entsoe_generation_b18)", "legendFormat": "Wind Offshore" },
    { "expr": "avg(entsoe_generation_b19)", "legendFormat": "Wind Onshore" }
   ]
  },
  {
   "title": "Energy ECO %",
   "type": "stat",
   "description": "Using data from https://transparency.entsoe.eu/",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(entsoe_generation_eco)*100", "legendFormat": "Engergy Index ECO %" }
   ]
  },
  {
   "title": "Energy Ampel",
   "type": "bargauge",
   "description": "Using data from https://transparency.entsoe.eu/",
   "gridPos": { "h": 12, "w": 4, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "avg(entsoe_generation_eco)", "legendFormat": "Engergy Index ECO %" }
   ]
  },
  {
   "title": "Energy FOS %",
   "type": "stat",
   "description": "Using data from https://transparency.entsoe.eu/",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(entsoe_generation_fos)*100", "legendFormat": "Engergy Index ECO %" }
   ]
  },
  {
   "title": "CO2g/w",
   "type": "timeseries",
   "description": "Using data from https://transparency.entsoe.eu/",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 13 },
   "targets": [
    { "expr": "avg(entsoe_generation_co2)", "legendFormat": "CO2 emmission" }
   ]
  },
  { "title": "Power Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Pod/Process Power Consumption (W) in Namespace: $namespace",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_package_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[5m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / PKG"
    },
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_dram_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[5m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / DRAM"
    },
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_other_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[5m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / OTHER"
    },
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_gpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[5m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / GPU"
    }
   ]
  },
  {
   "title": "Pod/Process CO2 FOS Emission (C02g/h) in Namespace: $namespace",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_package_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[5m])*(entsoe_generation_co2*3600))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / PKG"
    },
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_dram_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[5m])*($fosfactor/1000)*($ecofactor/1000))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / DRAM"
    },
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_other_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[5m])*($fosfactor/1000)*($ecofactor/1000))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / OTHER"
    },
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_gpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[5m])*($fosfactor/1000)*($ecofactor/1000))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / GPU"
    }
   ]
  },
  {
   "title": "Total Power Consumption (W) in Namespace: $namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(irate(kepler_container_package_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[5m]))",
     "legendFormat": "PKG"
    },
    {
     "expr": "sum(irate(kepler_container_dram_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[5m]))",
     "legendFormat": "DRAM"
    },
    {
     "expr": "sum(irate(kepler_container_other_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[5m]))",
     "legendFormat": "OTHER"
    },
    {
     "expr": "sum(irate(kepler_container_gpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[5m]))",
     "legendFormat": " GPU"
    }
   ]
  },
  {
   "title": "Total Power Consumption (kWh per day) in Namespace: $namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum (\n  increase(\n   (kepler_container_package_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[24h:1m])\n  )\n) * $watt_per_second_to_kWh",
     "legendFormat": "PKG (CORE+UNCORE)"
    },
    {
     "expr": "sum (\n  increase(\n   (kepler_container_dram_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[24h:1m])\n  )\n) * $watt_per_second_to_kWh",
     "legendFormat": "DRAM"
    },
    {
     "expr": "sum (\n  increase(\n   (kepler_container_other_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[24h:1m])\n  )\n) * $watt_per_second_to_kWh",
     "legendFormat": "OTHER"
    },
    {
     "expr": "sum (\n  increase(\n   (kepler_container_gpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[24h:1m])\n  )\n) * $watt_per_second_to_kWh",
     "legendFormat": " GPU"
    }
   ]
  },
  {
   "title": "Total Power Consumption (PKG+DRAM+OTHER+GPU) by Namespace (kWh per day)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container_namespace)(\n  (\n    increase(kepler_container_dram_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[24h:1m]) +\n    increase(kepler_container_other_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[24h:1m]) +\n    increase(kepler_container_package_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", cluster=~\"$meta_cluster\"}[24h:1m])\n  ) * $watt_per_second_to_kWh\n)",
     "legendFormat": "{{container_namespace}}"
    }
   ]
  }
 ]
}