apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: entsoe
  name: entsoe
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: entsoe
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: entsoe
    spec:
      containers:
      - image: "{{ .Values.entsoe.image.repository }}:{{ .Values.entsoe.image.tag }}"
        imagePullPolicy: {{ .Values.entsoe.image.pullPolicy }}
        name: entsoe
        ports:
          - containerPort: 9091
        env:
        - name: ensoe_api_key
          valueFrom:
            secretKeyRef:
              name: ensoe
              key: ensoe_api_key
        - name: PYTHONUNBUFFERED
          value: "1"
        #- name: https_proxy
        #  value: "http://10.105.124.65:8084"
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        supplementalGroups:
        - 1000
      terminationGracePeriodSeconds: 3
      volumes:
      - name: tmp
        emptyDir:
          medium: Memory
---
#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
#  annotations:
#  name: np-entsoe
#spec:
#  egress:
#  - ports:
#    - port: 8084
#      protocol: TCP
#    to:
#    - ipBlock:
#        cidr: 10.105.124.65/32
#  podSelector: {}
#  policyTypes:
#  - Egress
