name: Build Image
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            mtr.devops.telekom.de/caas/entsoe
            ghcr.io/caas-team/entsoe
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.2.0'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to MTR
        uses: docker/login-action@v3
        with:
          registry: mtr.devops.telekom.de
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            mtr.devops.telekom.de/caas/entsoe:latest
            ghcr.io/caas-team/entsoe:latest
            ${{ steps.meta.outputs.tags }}
  sign:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tags: ${{ needs.build.steps.meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v2
      - name: Sign Push
        run: |
          cosign sign --key env://COSIGN_KEY --tlog-upload=false ${{ matrix.tags }}
        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
